# Default Expandor Configuration
# This file provides minimal defaults so CLI can work out of the box
# Users can override by creating ~/.config/expandor/config.yaml

# Default model configuration
models:
  sdxl:
    model_id: "stabilityai/stable-diffusion-xl-base-1.0"
    dtype: "fp16"
    device: "cuda"
    enabled: true
  
# Default paths
paths:
  output_dir: "./expandor_output"
  cache_dir: null  # Use HuggingFace default
  stage_dir: "./expandor_stages"

# Default quality settings
quality:
  default_preset: "balanced"
  
# Default VRAM management
vram:
  auto_detect: true
  conservative_mode: false
  
# Default artifact detection
artifact_detection:
  enabled: true
  auto_fix: true