# Model-specific constraints
# From ai-wallpaper model configurations

sdxl:
  dimension_multiple: 8
  optimal_dimensions:
    - [1024, 1024]   # 1:1
    - [1152, 896]    # 4:3.11
    - [1216, 832]    # 3:2.05
    - [1344, 768]    # 16:9.14
    - [1536, 640]    # 2.4:1
    - [768, 1344]    # 9:16 (portrait)
    - [896, 1152]    # 3:4 (portrait)
    - [640, 1536]    # 1:2.4 (tall portrait)
  
  vram_requirements:
    base_overhead_mb: 6144
    attention_multiplier: 4
    safety_buffer: 0.2

flux:
  dimension_multiple: 16
  max_dimension: 2048
  optimal_pixels: 1048576  # 1MP
  fixed_generation_size: [1920, 1088]
  
  vram_requirements:
    base_overhead_mb: 12288  # 12GB
    attention_multiplier: 5
    safety_buffer: 0.25

dalle3:
  fixed_size: [1024, 1024]
  no_local_pipeline: true
  supports_inpainting: false

gpt_image_1:
  fixed_size: [1024, 1024]
  no_local_pipeline: true
  supports_inpainting: false

default:
  dimension_multiple: 8
  vram_requirements:
    base_overhead_mb: 8192
    attention_multiplier: 4
    safety_buffer: 0.2