# Strategy Default Parameters
# All strategy-specific values must be configured here
# NO HARDCODED VALUES in strategy implementations

progressive_outpaint:
  # Strength values for different stages
  outpaint_strength: 0.75  # Balance between generation and preservation
  min_strength: 0.20       # Minimum strength for final passes
  max_strength: 0.85       # Maximum strength - never go above this
  # Step ratios
  first_step_ratio: 2.0    # Initial expansion ratio
  middle_step_ratio: 1.5   # Middle step expansion ratio
  final_step_ratio: 1.3    # Final step expansion ratio
  # Other parameters
  max_supported: 8.0       # Maximum aspect ratio change supported
  base_mask_blur: 32       # Base blur value for masks
  base_steps: 60           # Base inference steps
  # Seam repair parameters
  seam_repair_steps: 30    # Steps for seam repair
  seam_repair_guidance: 5.0  # Lower guidance for blending
  
cpu_offload:
  # VRAM management
  safety_factor: 0.6       # VRAM safety factor for CPU offload
  pipeline_vram: 1024      # Max VRAM with offloading (1GB)
  conservative_safety_factor: 0.5  # Very conservative for CPU offload
  # Processing parameters
  processing_steps: 3      # Multiple small steps for processing
  # Tile generation
  tile_generation_strength: 0.9   # For initial tile generation
  tile_generation_steps: 25       # Fewer steps for speed
  tile_generation_guidance: 7.0   # Guidance scale for generation
  # Tile refinement
  tile_refinement_strength: 0.3   # For refining tile edges
  tile_refinement_steps: 20       # Steps for refinement
  tile_refinement_guidance: 7.0   # Guidance scale for refinement
  
tiled_expansion:
  # Tile size parameters
  default_tile_size: 1024  # Default tile size
  min_tile_size: 512       # Minimum tile size
  max_tile_size: 2048      # Maximum tile size
  overlap: 256             # Tile overlap size
  blend_width: 256         # Width of blending region between tiles
  # Refinement parameters
  refinement_strength: 0.2        # Very light refinement to preserve details
  refinement_steps: 20            # Steps for refinement
  refinement_guidance: 6.5        # Lower guidance for preservation
  # Edge fixing
  edge_fix_strength: 0.3          # Lower strength to preserve tile coherence
  edge_fix_steps: 30              # Steps for edge fixing
  edge_fix_guidance: 7.0          # Guidance for edge fixing
  # Final pass
  final_pass_strength: 0.4        # Much lower for tile processing
  final_pass_steps: 40            # Steps for final pass
  final_pass_guidance: 7.0        # Guidance for final pass
  
swpo_strategy:
  # Window processing parameters
  blur_radius: 50                 # Radius for edge filling
  noise_strength: 0.02            # Strength for noise addition to mask
  # Light touch parameters
  light_touch_steps: 30           # Steps for light touch
  light_touch_guidance: 7.0       # Guidance scale
  # Edge detection
  edge_sampling_width: 10         # Width for edge sampling
  max_edge_distance: 100          # Maximum distance for edge detection
  
smart_refiner:
  # Base refinement parameters
  base_strength: 0.4              # Default strength for refinement
  min_region_size: 32             # Minimum region size
  # Refinement parameters
  refinement_steps: 30            # Steps for refinement
  refinement_guidance: 7.5        # Guidance scale
  # Blur radii by boundary size
  large_boundary_blur: 32         # Blur radius for large boundaries
  medium_boundary_blur: 16        # Blur radius for medium boundaries
  small_boundary_blur: 24         # Blur radius for small boundaries
  
seam_repair:
  # Mask blur parameters
  mask_blur_radius: 5             # Gaussian blur radius for mask
  blend_mask_blur_radius: 10      # Blur radius for blend mask
  final_blur_radius: 2            # Small blur for final result
  # Repair strengths
  seam_repair_strength: 0.8       # High strength for seam repair
  seam_repair_guidance: 7.5       # Guidance scale
  seam_repair_steps: 50           # Inference steps
  # Artifact repair
  base_blur_strength: 0.2         # Base strength for blur
  artifact_repair_strength: 0.5   # Strength for artifact regions
  artifact_repair_guidance: 7.5   # Guidance scale
  artifact_repair_steps: 30       # Inference steps
  # Final blend
  final_blend_strength: 0.4       # Final blending strength
  final_blend_guidance: 7.5       # Guidance scale
  final_blend_steps: 40           # Inference steps
  
edge_analysis:
  # Edge detection
  edge_threshold: 100             # Edge detection threshold
  # Edge refinement
  edge_refinement_strength: 0.8   # For refining detected edges
  soft_edge_strength: 0.5         # For soft edge blending
  # Sensitivity thresholds
  edge_detection_sensitivity: 0.1 # Edge detection sensitivity
  seam_detection_sensitivity: 0.3 # Seam detection sensitivity
  artifact_detection_sensitivity: 0.5  # Artifact detection sensitivity
  
controlnet_progressive:
  # VRAM priority
  vram_priority: 4                # Priority for VRAM allocation
  # Inpaint mask
  inpaint_mask_color: 255         # White color for inpaint mask
  
diffusers_adapter:
  # Default generation parameters
  controlnet_strength_default: 0.8
  img2img_strength_default: 0.75
  num_inference_steps_default: 50  # Default inference steps
  guidance_scale_default: 7.5      # Default guidance scale
  # Enhancement parameters
  enhancement_strength: 0.3        # Low strength for enhancement operations
  # Dimension constraints
  sdxl_dimension_multiple: 8       # SDXL dimension multiple
  max_dimension: 4096              # Maximum dimension for images
  
hybrid_adaptive:
  # Threshold parameters
  aspect_ratio_threshold: 0.2      # 20% change triggers outpainting
  extreme_ratio_threshold: 3.0     # 3x+ ratio triggers SWPO
  # Quality estimates for different strategies
  direct_upscale_quality: 0.9      # Direct upscale quality estimate
  progressive_quality: 0.85        # Progressive quality estimate
  swpo_quality: 0.85               # SWPO quality estimate
  tiled_quality: 0.7               # Tiled quality estimate
  mixed_strategy_quality: 0.85     # Mixed strategy quality
  fallback_quality: 0.8            # Fallback quality
  default_quality: 0.9             # Default quality
  hybrid_plan_quality: 0.7         # Hybrid plan quality