# Strategy Configurations
# Adapted from ai-wallpaper resolution.yaml and models.yaml

progressive_outpainting:
  enabled: true
  aspect_ratio_thresholds:
    moderate: 1.5      # Use for aspect changes > 1.5x
    extreme: 4.0       # Switch to SWPO for > 4.0x
    max_supported: 8.0 # Maximum supported ratio
  
  expansion_ratios:
    first_step: 1.4    # Conservative first expansion
    middle_steps: 1.25 # Middle expansions
    final_step: 1.15   # Final touch-up
  
  outpaint_settings:
    denoising_strength: 0.95
    min_strength: 0.20
    mask_blur_base: 32
    inference_steps: 60
    prompt_suffix: ", seamless expansion, extended scenery, natural continuation"
  
  adaptive_settings:
    blur_multipliers:
      small: 1.0   # expansion < 1.3x
      medium: 1.2  # expansion 1.3-1.6x
      large: 1.5   # expansion > 1.6x
    
    step_multipliers:
      initial: 1.2   # More steps for first expansion
      middle: 1.0    # Normal steps
      final: 0.8     # Fewer steps for final

swpo:  # Sliding Window Progressive Outpainting
  enabled: true
  window_size: 200
  overlap_ratio: 0.8
  denoising_strength: 0.95
  edge_blur_width: 20
  clear_cache_every_n_windows: 5
  final_unification_pass: true
  unification_strength: 0.15

direct_upscale:
  models:
    default: "RealESRGAN_x4plus"
    fast: "RealESRGAN_x2plus"
    anime: "RealESRGAN_x4plus_anime_6B"
  
  tile_sizes:
    low_vram: 512
    medium_vram: 768
    high_vram: 1024
    unlimited: 2048
  
  fp32: true  # Use FP32 for maximum quality

tiled_expansion:
  tile_size: 1024
  overlap: 256
  blend_width: 128
  min_tile_size: 512
  max_tile_size: 2048

quality_validation:
  artifact_detection:
    aggressive:
      color_threshold: 10
      gradient_multiplier: 2.0
      frequency_multiplier: 1.5
      min_seam_width: 5
      max_seam_width: 20
    
    standard:
      color_threshold: 15
      gradient_multiplier: 2.5
      frequency_multiplier: 2.0
      min_seam_width: 3
      max_seam_width: 15
    
    light:
      color_threshold: 20
      gradient_multiplier: 3.0
      frequency_multiplier: 2.5
      min_seam_width: 2
      max_seam_width: 10