# Expandor Strategy Configurations
# Each strategy has specific parameters and constraints

strategies:
  direct_upscale:
    # Simple upscaling without AI generation
    name: "Direct Upscale"
    description: "Fast upscaling using Real-ESRGAN or similar models"
    priority: 1  # Lowest priority, used as fallback
    requirements:
      min_vram_mb: 2000
      supports_any_ratio: true
    parameters:
      upscale_model: "realesrgan"  # or "esrgan", "swinir"
      tile_size: 512  # For tiled processing if needed
      tile_overlap: 32
    constraints:
      max_scale_factor: 4  # Don't upscale more than 4x in one pass
    
  progressive_outpaint:
    # Main strategy for aspect ratio changes
    name: "Progressive Outpainting"
    description: "Gradually expands image maintaining context"
    priority: 3  # Higher priority for aspect ratio changes
    requirements:
      min_vram_mb: 4000
      requires_inpaint_pipeline: true
    parameters:
      # Expansion ratios for each step
      first_step_ratio: 1.4  # Conservative first expansion
      middle_step_ratio: 1.25
      final_step_ratio: 1.15
      # Denoising strengths
      base_strength: 0.95  # High for content generation
      strength_decay: 0.85  # Multiply each step
      min_strength: 0.35  # Never go below this
      # Mask parameters
      mask_blur_percentage: 0.4  # 40% of expansion size
      mask_mode: "gradient"  # or "hard", "gaussian"
      # Edge handling
      edge_blend_width: 64  # Pixels to blend at edges
      pre_fill_mode: "mirror"  # or "stretch", "wrap"
      # From hardcoded values
      max_supported: 8.0       # Maximum aspect ratio change supported
      min_strength_value: 0.20 # Minimum strength for operations
      max_strength_value: 0.85 # Maximum strength for operations
      first_step_ratio_value: 2.0  # First expansion ratio
      middle_step_ratio_value: 1.5 # Middle step expansion ratio
      final_step_ratio_value: 1.3  # Final step expansion ratio
      base_mask_blur: 32       # Base blur value for masks
      base_steps: 60           # Base inference steps
      # Seam repair parameters
      seam_repair_steps: 30    # Steps for seam repair
      seam_repair_guidance: 5.0  # Lower guidance for blending
    constraints:
      max_aspect_ratio_change: 8.0  # Maximum ratio change
      min_dimension: 512  # Don't shrink below this
    
  tiled_expansion:
    # Memory-efficient strategy for large images
    name: "Tiled Expansion"
    description: "Process image in tiles for low VRAM situations"
    priority: 2  # Used when memory is constrained
    requirements:
      min_vram_mb: 2000
      supports_tiling: true
    parameters:
      tile_size: 768  # Size of each tile
      tile_overlap: 128  # Overlap between tiles
      blend_mode: "feather"  # or "linear", "gaussian"
      # Processing order
      tile_order: "spiral"  # or "raster", "random"
      # Memory management
      process_batch_size: 1  # Tiles to process simultaneously
      clear_cache_every: 4  # Clear VRAM every N tiles
      # From hardcoded values
      default_tile_size: 1024  # Default tile size
      min_tile_size: 512       # Minimum tile size
      max_tile_size: 2048      # Maximum tile size
      overlap: 256             # Tile overlap size
      blend_width: 256         # Width of blending region between tiles
      # Refinement parameters
      refinement_strength: 0.2        # Very light refinement to preserve details
      refinement_steps: 20            # Steps for refinement
      refinement_guidance: 6.5        # Lower guidance for preservation
      # Edge fixing
      edge_fix_strength: 0.3          # Lower strength to preserve tile coherence
      edge_fix_steps: 30              # Steps for edge fixing
      edge_fix_guidance: 7.0          # Guidance for edge fixing
      # Final pass
      final_pass_strength: 0.4        # Much lower for tile processing
      final_pass_steps: 40            # Steps for final pass
      final_pass_guidance: 7.0        # Guidance for final pass
    constraints:
      max_image_size: 16384  # Maximum dimension
      min_tile_size: 512
  
  swpo:
    # Sliding Window Progressive Outpainting
    name: "SWPO (Sliding Window)"
    description: "Advanced strategy for extreme aspect ratios"
    priority: 4  # Highest priority for extreme cases
    requirements:
      min_vram_mb: 6000
      requires_inpaint_pipeline: true
    parameters:
      # Window parameters
      window_size: 256  # Width of expansion window
      overlap_ratio: 0.8  # 80% overlap between windows
      # Expansion strategy
      expansion_mode: "bidirectional"  # or "left_to_right", "center_out"
      # Quality settings
      inference_steps_multiplier: 1.2  # More steps for quality
      # Boundary handling
      boundary_fade_width: 32
      # Memory optimization
      clear_cache_frequency: 5  # Every N windows
      # Final unification
      unification_pass: true
      unification_strength: 0.3
      # From hardcoded values
      blur_radius: 50                 # Radius for edge filling
      noise_strength: 0.02            # Strength for noise addition to mask
      # Light touch parameters
      light_touch_steps: 30           # Steps for light touch
      light_touch_guidance: 7.0       # Guidance scale
      # Edge detection
      edge_sampling_width: 10         # Width for edge sampling
      max_edge_distance: 100          # Maximum distance for edge detection
    constraints:
      min_aspect_ratio_change: 2.0  # Only use for significant changes
      max_windows_per_direction: 50
  
  cpu_offload:
    # Low VRAM strategy with CPU offloading
    name: "CPU Offload"
    description: "Offload model components to CPU to save VRAM"
    priority: 2  # Same as tiled, chosen based on VRAM
    requirements:
      min_vram_mb: 1000
      min_ram_mb: 16000  # Needs significant RAM
      supports_cpu_offload: true
    parameters:
      offload_mode: "sequential"  # or "model_split", "layer_wise"
      keep_in_vram: ["vae"]  # Components to keep on GPU
      # Performance tuning
      attention_slicing: true
      attention_slice_size: 4
      # Memory thresholds
      vram_threshold_mb: 1500  # Start offloading below this
      # Processing adjustments
      batch_size: 1  # Reduce batch size
      gradient_checkpointing: true
      # VRAM management (from hardcoded values)
      safety_factor: 0.6       # VRAM safety factor for CPU offload
      pipeline_vram: 1024      # Max VRAM with offloading (1GB)
      conservative_safety_factor: 0.5  # Very conservative for CPU offload
      # Processing parameters
      processing_steps: 3      # Multiple small steps for processing
      # Tile generation
      tile_generation_strength: 0.9   # For initial tile generation
      tile_generation_steps: 25       # Fewer steps for speed
      tile_generation_guidance: 7.0   # Guidance scale for generation
      # Tile refinement
      tile_refinement_strength: 0.3   # For refining tile edges
      tile_refinement_steps: 20       # Steps for refinement
      tile_refinement_guidance: 7.0   # Guidance scale for refinement
    constraints:
      max_resolution: 2048  # CPU is slower, limit size
      
  hybrid_adaptive:
    # Intelligent strategy selection based on conditions
    name: "Hybrid Adaptive"
    description: "Dynamically combines strategies based on requirements"
    priority: 5  # Highest priority when applicable
    requirements:
      min_vram_mb: 4000
      requires_strategy_selector: true
    parameters:
      # Analysis phase
      analyze_image: true
      detect_content_type: true  # photo, art, text, etc.
      # Strategy selection rules
      rules:
        - condition: "aspect_ratio_change > 4"
          strategy: "swpo"
        - condition: "vram_available < 3000"
          strategy: "tiled_expansion"
        - condition: "dimension > 4096"
          strategy: "tiled_expansion"
        - condition: "content_type == 'text'"
          strategy: "progressive_outpaint"  # Better for text preservation
      # Combination modes
      can_combine: true  # Can use multiple strategies
      combination_rules:
        - primary: "swpo"
          secondary: "cpu_offload"
          condition: "vram_available < 6000"
    constraints:
      max_strategy_switches: 3  # Don't switch too often

# Global strategy settings
global:
  # Automatic fallback chain when strategy fails
  fallback_chain:
    - hybrid_adaptive
    - swpo
    - progressive_outpaint
    - tiled_expansion
    - cpu_offload
    - direct_upscale
  
  # Strategy selection preferences
  selection:
    prefer_quality: true  # Quality over speed
    auto_select: true  # Automatic selection based on image
    respect_user_override: true  # --strategy flag overrides auto
    
  # Memory management
  memory:
    aggressive_cleanup: false  # Clear cache aggressively
    pre_allocate: false  # Pre-allocate VRAM
    safety_margin_mb: 500  # Keep this much VRAM free