# Default Expandor Configuration
# This file provides minimal defaults so CLI can work out of the box
# Users can override by creating ~/.config/expandor/config.yaml

# Model configurations
models:
  sdxl:
    model_id: "stabilityai/stable-diffusion-xl-base-1.0"
    dtype: "fp16"
    device: "cuda"
    enabled: true

# Default settings (flat structure for UserConfig)
default_quality: "balanced"
default_device: "cuda"
default_dtype: "fp16"
cache_directory: null  # Use HuggingFace default

# User preferences
auto_artifact_detection: true
use_controlnet: true
save_intermediate_stages: false
verbose_logging: false

# Performance settings
max_vram_usage_mb: null  # Auto-detect
allow_cpu_offload: true
allow_tiled_processing: true
clear_cache_frequency: 5

# Output settings
output_format: "png"
output_compression: 0
default_output_dir: "./expandor_output"