# Expandor Quality Presets Configuration
# Defines quality levels with their associated parameters

quality_presets:
  custom:
    # Base defaults when no preset specified
    name: "Custom Settings"
    description: "Base default values - used when no preset selected"
    priority: 0  # Lowest priority - overridden by any preset
    
    # Generation parameters
    generation:
      num_inference_steps: 30
      guidance_scale: 7.5
      scheduler: "EulerAncestralDiscreteScheduler"
      use_karras_sigmas: false
      
    # Resolution handling
    resolution:
      prefer_native: true
      upscale_method: "real-esrgan"
      upscale_denoise: 0.2
      
    # Expansion parameters
    expansion:
      denoising_strength: 0.7
      mask_blur_ratio: 0.4
      overlap_ratio: 0.7
      edge_blend_pixels: 96
      
    # Quality validation
    validation:
      enable_artifact_detection: true
      artifact_threshold: 0.1
      enable_seam_detection: true
      seam_threshold: 0.1
      max_repair_attempts: 3
      
    # Performance trade-offs
    performance:
      enable_xformers: true
      enable_cpu_offload: false
      tile_processing: false
      batch_size: 1
      
    # Model selection
    models:
      prefer_refiner: false
      refiner_strength: 0.3
      controlnet_strength: 0.25
      
    # Output settings
    output:
      format: "png"
      compression: 0
      save_intermediate: false
      
  ultra:
    # Maximum quality, no compromise
    name: "Ultra Quality"
    description: "Highest quality with maximum processing time"
    priority: 4  # Highest priority
    
    # Generation parameters
    generation:
      num_inference_steps: 50  # Optimal steps (diminishing returns above 50)
      guidance_scale: 8.0  # Optimal guidance (91% success rate at 7-8)
      scheduler: "EulerAncestralDiscreteScheduler"  # Sharpest results per research
      use_karras_sigmas: true  # Better noise schedule
      
    # Resolution handling
    resolution:
      prefer_native: true  # Use model's preferred resolution
      upscale_method: "real-esrgan"  # Best upscaler
      upscale_denoise: 0.2  # Light denoising during upscale
      
    # Expansion parameters
    expansion:
      denoising_strength: 0.70  # Optimal for quality without destroying content
      mask_blur_ratio: 0.5  # 50% blur for smoother transitions
      overlap_ratio: 0.85  # High overlap in SWPO
      edge_blend_pixels: 128  # Wide blending zone
      
    # Quality validation
    validation:
      enable_artifact_detection: true
      artifact_threshold: 0.1  # Very sensitive
      enable_seam_detection: true
      seam_threshold: 0.05  # Detect subtle seams
      max_repair_attempts: 5  # Try harder to fix issues
      
    # Performance trade-offs
    performance:
      enable_xformers: true  # Memory efficient attention
      enable_cpu_offload: false  # Keep on GPU for speed
      tile_processing: false  # Avoid tiling if possible
      batch_size: 1  # Focus on single image quality
      
    # Model selection
    models:
      prefer_refiner: true  # Use SDXL refiner if available
      refiner_strength: 0.3  # Refiner denoising strength
      controlnet_strength: 0.25  # Optimal starting point for balanced results
      
    # Output settings
    output:
      format: "png"
      compression: 0  # No compression
      save_intermediate: true  # Save all stages
      
  high:
    # High quality with reasonable speed
    name: "High Quality"
    description: "Excellent quality with good performance balance"
    priority: 3
    
    generation:
      num_inference_steps: 50  # Good quality/speed balance
      guidance_scale: 7.5  # Standard guidance
      scheduler: "EulerAncestralDiscreteScheduler"  # Fast and good
      use_karras_sigmas: true
      
    resolution:
      prefer_native: true
      upscale_method: "real-esrgan"
      upscale_denoise: 0.3
      
    expansion:
      denoising_strength: 0.65  # Optimal for expansions
      mask_blur_ratio: 0.4  # 40% blur
      overlap_ratio: 0.75  # Good overlap
      edge_blend_pixels: 96
      
    validation:
      enable_artifact_detection: true
      artifact_threshold: 0.2  # Less sensitive
      enable_seam_detection: true
      seam_threshold: 0.1
      max_repair_attempts: 3
      
    performance:
      enable_xformers: true
      enable_cpu_offload: false
      tile_processing: false
      batch_size: 1
      
    models:
      prefer_refiner: true
      refiner_strength: 0.25
      controlnet_strength: 0.35  # Slightly higher than ultra for high preset
      
    output:
      format: "png"
      compression: 3  # Light compression
      save_intermediate: false
      
  balanced:
    # Default preset - good for most use cases
    name: "Balanced Quality"
    description: "Good quality with reasonable processing time"
    priority: 2  # Default priority
    
    generation:
      num_inference_steps: 35  # Moderate steps
      guidance_scale: 7.0  # Standard guidance
      scheduler: "EulerDiscreteScheduler"  # Fast and stable
      use_karras_sigmas: false
      
    resolution:
      prefer_native: false  # Allow non-native for speed
      upscale_method: "bicubic"  # Faster upscaling
      upscale_denoise: 0.0  # No denoising
      
    expansion:
      denoising_strength: 0.60  # Lower end of optimal range
      mask_blur_ratio: 0.35  # 35% blur
      overlap_ratio: 0.6  # Moderate overlap
      edge_blend_pixels: 64
      
    validation:
      enable_artifact_detection: true
      artifact_threshold: 0.3  # Moderate sensitivity
      enable_seam_detection: false  # Skip for speed
      seam_threshold: 0.15
      max_repair_attempts: 2
      
    performance:
      enable_xformers: true
      enable_cpu_offload: true  # Allow if needed
      tile_processing: true  # Allow for large images
      batch_size: 2  # Some batching okay
      
    models:
      prefer_refiner: false  # Skip refiner for speed
      refiner_strength: 0.2
      controlnet_strength: 0.5  # Higher end of optimal range
      
    output:
      format: "png"
      compression: 6  # Moderate compression
      save_intermediate: false
      
  fast:
    # Speed priority for quick results
    name: "Fast Processing"
    description: "Fastest processing with acceptable quality"
    priority: 1  # Lowest priority
    
    generation:
      num_inference_steps: 20  # Minimum viable steps
      guidance_scale: 6.0  # Lower guidance for speed
      scheduler: "DDIMScheduler"  # Fastest scheduler
      use_karras_sigmas: false
      
    resolution:
      prefer_native: false
      upscale_method: "bilinear"  # Fastest upscaling
      upscale_denoise: 0.0
      
    expansion:
      denoising_strength: 0.65  # Lower for speed
      mask_blur_ratio: 0.25  # Minimal blur
      overlap_ratio: 0.4  # Less overlap
      edge_blend_pixels: 32  # Narrow blend
      
    validation:
      enable_artifact_detection: false  # Skip validation
      artifact_threshold: 0.5
      enable_seam_detection: false
      seam_threshold: 0.25
      max_repair_attempts: 0  # No repairs
      
    performance:
      enable_xformers: true
      enable_cpu_offload: true
      tile_processing: true
      batch_size: 4  # Batch for speed
      
    models:
      prefer_refiner: false
      refiner_strength: 0.0  # No refiner
      controlnet_strength: 0.5  # Still within optimal range
      
    output:
      format: "jpeg"  # Smaller files
      compression: 85  # JPEG quality
      save_intermediate: false

# Global quality settings
global:
  # Default preset if not specified
  default_preset: "custom"
  
  # Automatic quality selection based on image
  auto_select:
    enabled: true
    rules:
      - condition: "resolution > 4096"
        preset: "fast"  # Large images need speed
      - condition: "aspect_ratio_change > 4"
        preset: "high"  # Extreme changes need quality
      - condition: "vram_available < 4000"
        preset: "fast"  # Low VRAM needs efficiency
        
  # Quality scaling based on system resources
  adaptive_quality:
    enabled: true
    min_steps: 15  # Never go below this
    max_steps: 100  # Never exceed this
    vram_scaling: true  # Adjust based on VRAM
    
  # Validation overrides
  validation:
    always_validate_ultra: true  # Always validate ultra preset
    skip_validation_on_error: false  # Don't skip on errors
    
  # Output quality settings
  output:
    preserve_metadata: true  # Keep EXIF/metadata
    optimize_filesize: false  # Quality over size
    max_dimension: 16384  # Safety limit