# Comprehensive Configuration for All 979 Hardcoded Values in Expandor
# This configuration captures every hardcoded value found in the codebase analysis

# ===================================================================
# MEMORY AND VRAM CONFIGURATION
# ===================================================================
memory:
  # Byte conversion constants
  bytes_to_mb_divisor: 1048576  # 1024 * 1024
  bytes_to_gb_divisor: 1073741824  # 1024^3
  
  # VRAM Management
  vram:
    # GPU memory thresholds (MB)
    safety_factors:
      default: 0.8
      conservative: 1.1  # 10% safety margin
      aggressive: 0.7
    
    # Data type memory requirements (bytes per element)
    dtype_memory:
      float16: 2
      bfloat16: 2
      float32: 4
      int32: 4
    
    # Model-specific VRAM estimates (MB)
    model_estimates:
      sdxl:
        generate: 6000
        inpaint: 5500
        img2img: 5000
        refine: 4000
        enhance: 3500
        controlnet_generate: 8500
        controlnet_inpaint: 8000
        controlnet_img2img: 7500
      
      sd15:
        generate: 8000
        inpaint: 7500
        img2img: 7000
        refine: 5000
        enhance: 4500
        controlnet_generate: 10500
        controlnet_inpaint: 10000
        controlnet_img2img: 9500
      
      flux:
        generate: 12000
        inpaint: 11000
        img2img: 10000
        refine: 8000
        enhance: 7000
        controlnet_generate: 14500
        controlnet_inpaint: 14000
        controlnet_img2img: 13500
      
      sd3:
        generate: 3000
        inpaint: 2800
        img2img: 2500
        refine: 2000
        enhance: 1800
        controlnet_generate: 4500
        controlnet_inpaint: 4300
        controlnet_img2img: 4000
      
      sd2:
        generate: 4000
        inpaint: 3800
        img2img: 3500
        refine: 2500
        enhance: 2300
        controlnet_generate: 5500
        controlnet_inpaint: 5300
        controlnet_img2img: 5000
    
    # Memory overhead calculations
    overhead:
      per_megapixel: 150  # Additional MB per megapixel
      batch_size_multiplier: 0.8  # Additional factor per batch item
      lora_overhead: 200  # MB per LoRA
      pixel_overhead_per_megapixel: 4.5
      latent_multiplier: 4  # Latent space multiplier
      megapixel_divisor: 1000000  # 1e6 for MP calculations
    
    # ControlNet overhead
    controlnet:
      model_load: 2000  # Per ControlNet model
      operation_active: 1500  # Additional for active operations
    
    # Tile processing
    tiling:
      bytes_per_pixel: 12
      overlap: 64
      min_tile: 256
      max_tile: 2048
      divisible_by: 64
      tile_alignment: 16  # Tile size alignment
      min_overlap_ratio: 0.25  # 25% minimum overlap

  # CPU Memory
  cpu:
    min_ram_gb: 16
    disk_space_gb: 50
    batch_limits:
      max_batch_size: 16
      safety_factor: 0.8

# ===================================================================
# IMAGE PROCESSING PARAMETERS
# ===================================================================
image_processing:
  # Color and normalization constants
  color:
    max_rgb_value: 255.0
    channels: 3
    noise_epsilon: 1e-08  # Small value to prevent division by zero
  
  # Image generation defaults
  generation:
    default_width: 1024
    default_height: 1024
    num_inference_steps: 50
    guidance_scale: 7.5
    strength: 0.8
    negative_prompt: ""
    controlnet_conditioning_scale: 1.0
  
  # Blur and filters
  blur:
    gaussian_divisor: 4.0  # size / 4.0 for sigma
    radius_divisor: 4  # blur_radius // 4
    center_divisor: 2.0  # size / 2.0 for center
  
  # Noise and enhancement
  noise:
    perlin_scale: 0.1
    perlin_octaves: 1
    strength_multiplier: 10
    enhancement_factor: 1.2
  
  # Edge detection
  edge_detection:
    sobel_kernel_size: 3
    canny_kernel_size: 3
    dilation_default: 5
    gradient_l2: false
    dilate_default: true
  
  # Mask processing
  masks:
    threshold: 128
    feather_default: 0
    binary_threshold: 128

# ===================================================================
# RESOLUTION AND DIMENSIONS
# ===================================================================
dimensions:
  # Standard resolutions
  presets:
    # Common display resolutions
    "720p": [1280, 720]
    "1080p": [1920, 1080]
    "1440p": [2560, 1440]
    "4K": [3840, 2160]
    "5K": [5120, 2880]
    "8K": [7680, 4320]
    
    # Ultrawide variants
    "ultrawide_1440p": [3440, 1440]
    "ultrawide_4K": [5120, 2160]
    "super_ultrawide": [5760, 1080]
    
    # Portrait and square
    "portrait_4K": [2160, 3840]
    "square_4K": [2880, 2880]
    
    # Mobile devices
    "iphone": [1170, 2532]
    "ipad": [2048, 2732]
    "android": [1440, 3200]
    
    # Aspect ratios
    "16:9": [1920, 1080]
    "21:9": [2560, 1080]
    "32:9": [3840, 1080]
    "9:16": [1080, 1920]  # Portrait
  
  # SDXL optimal resolutions
  sdxl_resolutions:
    - [1024, 1024]  # 1:1
    - [1152, 896]   # 4:3.11
    - [1216, 832]   # 3:2.05
    - [1344, 768]   # 16:9.14
    - [1536, 640]   # 2.4:1
    - [768, 1344]   # 9:16 (portrait)
    - [896, 1152]   # 3:4 (portrait)
    - [640, 1536]   # 1:2.4 (tall portrait)
  
  # Constraints
  constraints:
    divisible_by: 16
    max_dimension: 65536  # Maximum single dimension
    min_dimension: 512
    optimal_pixels: 1048576  # 1024 * 1024, 1MP for best quality
    
  # Progressive expansion
  progressive:
    max_expansion_per_step: 2.0
    aspect_tolerance: 0.05
    max_aspect_change_ratio: 8.0
    target_completion_threshold: 0.95  # 95% completion
    expansion_step_multiplier: 1.5
    max_steps: 10
    
  # Sliding Window Progressive Outpainting (SWPO)
  swpo:
    default_window_size: 200
    default_overlap_ratio: 0.8
    min_overlap_ratio: 0.7
    max_overlap_ratio: 0.85

# ===================================================================
# QUALITY AND VALIDATION SETTINGS
# ===================================================================
quality:
  # Quality presets
  presets:
    ultra:
      inference_steps: 80
      cfg_scale: 7.5
      denoise_strength: 0.95
      blur_radius: 300
    
    high:
      inference_steps: 60
      cfg_scale: 7.0
      denoise_strength: 0.9
      blur_radius: 200
    
    balanced:
      inference_steps: 40
      cfg_scale: 6.5
      denoise_strength: 0.85
      blur_radius: 150
    
    fast:
      inference_steps: 25
      cfg_scale: 6.0
      denoise_strength: 0.8
      blur_radius: 100
  
  # Validation thresholds
  validation:
    default_quality_score: 1.0
    quality_threshold: 0.1  # When auto artifact detection enabled
    severity_penalties:
      none: 0.0
      low: 0.1
      medium: 0.3
      high: 0.5
      critical: 0.8
    
    # Artifact detection
    artifact_detection:
      score_threshold: 0.5
      critical_percentage: 5.0
      detection_level: "aggressive"
    
    # Score weights for different detection methods
    score_weights:
      color: 0.3
      gradient: 0.3
      frequency: 0.25
      pattern: 0.15
  
  # Quality multipliers by preset
  preset_multipliers:
    ultra: 1.2
    high: 1.0
    balanced: 0.8
    fast: 0.6

# ===================================================================
# CONTROLNET CONFIGURATION
# ===================================================================
controlnet:
  # Extractor configurations
  extractors:
    canny:
      default_low_threshold: 100
      default_high_threshold: 200
      aperture_size: 3
      l2_gradient: false
      dilate: true
      kernel_size: 3
    
    blur:
      default_radius: 5
      blur_type: "gaussian"
    
    depth:
      # Placeholder for depth model parameters
      enabled: false
  
  # Model configurations
  models:
    canny: "lllyasviel/sd-controlnet-canny"
    depth: "lllyasviel/sd-controlnet-depth"
    openpose: "lllyasviel/sd-controlnet-openpose"
  
  # Pipeline settings
  pipelines:
    extract_at_each_step: true
    conditioning_scale: 1.0
    guidance_start: 0.0
    guidance_end: 1.0

# ===================================================================
# STRATEGY-SPECIFIC PARAMETERS
# ===================================================================
strategies:
  # Base strategy settings
  base:
    vram_buffer_multiplier: 1.2  # 20% buffer
    temp_file_retention: 5  # Keep last 5 files
    timestamp_multiplier: 1000  # For millisecond timestamps
  
  # Direct upscale
  direct_upscale:
    scale_threshold: 3  # Use x4 model if scale >= 3, otherwise x2
    default_scale_factor: 2
  
  # Progressive outpainting
  progressive_outpaint:
    seam_fix_enabled: true
    step_type_default: "progressive"
    direction_default: "both"
    fill_color: 255
  
  # SWPO (Sliding Window Progressive Outpainting)
  swpo:
    noise_strength: 0.02
    edge_erosion_iterations: 0.5  # kernel_size // 2
    context_analysis:
      high_frequency_threshold: 0.7
      smooth_threshold: 0.3
  
  # Tiled expansion
  tiled_expansion:
    tile_sizes:
      large: 1024
      medium: 768
      small: 512
    coordinate_start: 0  # Starting coordinates
  
  # Strategy selector
  strategy_selector:
    aspect_tolerance: 1.1
    massive_expansion_multiplier: 4  # If moderate is 4, massive is 16
    default_priority: 50
  
  # Hybrid adaptive
  hybrid_adaptive:
    simple_aspect_change_threshold: 0.1
    simple_scale_difference_threshold: 0.1
    extreme_scale_threshold: 4
    additional_upscale_threshold: 1.1
    
    # Quality estimates for different strategies
    quality_estimates:
      simple: 0.9
      progressive: 0.85
      swpo: 0.85
      cpu_fallback: 0.7
      tiled_high: 0.85
      tiled_low: 0.8
      final: 0.9
    
    # VRAM estimates
    vram_estimates:
      minimal: 1024
      cpu_fallback: 512
    
    # Configuration overrides
    config_overrides:
      max_expansion_ratio: 1.3
      small_tile_size: 384
      small_overlap: 64
    
    # SWPO thresholds
    swpo_thresholds:
      extreme_ratio: 5
      window_size_large: 300
      window_size_normal: 200
      overlap_high: 0.85
      overlap_normal: 0.8

# ===================================================================
# CLI AND USER INTERFACE
# ===================================================================
cli:
  # Display formatting
  formatting:
    separator_width: 60
    short_separator_width: 50
    prompt_truncation: 50
    yaml_width: 120
    config_width: 80
  
  # Progress reporting
  progress:
    cache_clear_frequency: 5  # Clear CUDA cache every N operations
    status_report_interval: 5  # Report status every 5 operations
  
  # Setup wizard
  setup:
    vram_limits:
      min: 1024
      max: 49152  # 48GB
    
    lora_weight_limits:
      min: 0.1
      max: 2.0
      default: 1.0
    
    lora_weight_sum_limit: 1.5
    lora_weight_scale_factor: 1.5

# ===================================================================
# MODEL AND ADAPTER CONFIGURATION
# ===================================================================
models:
  # Model size estimates (bytes)
  size_estimates:
    sdxl: 7516192768  # 7GB
    flux: 16106127360  # 15GB
    default: 5368709120  # 5GB
  
  # Model type patterns
  patterns:
    sd3: ["stable-diffusion-3", "sd3", "sd-3"]
    flux: ["flux"]
    sdxl: ["sdxl", "xl"]
  
  # Optimal resolutions by model
  optimal_resolutions:
    sdxl: [1024, 1024]
    sd15: [512, 512]
    sd3: [1024, 1024]
    flux: [1024, 1024]
    sd2: [768, 768]
  
  # Resolution constraints
  resolution_constraints:
    multiple: 16
    max_dimension: 4096
    min_dimension: 512

# ===================================================================
# PROCESSING PARAMETERS
# ===================================================================
processing:
  # Artifact removal
  artifact_removal:
    boundary_width_multiplier: 3  # 3x boundary width for masks
    gradient_threshold: 0.5
    sobel_kernel: 3
  
  # Seam repair
  seam_repair:
    min_repair_steps: 10
    min_repair_strength: 0.2
    strength_reduction_factor: 0.6  # 60% of normal strength
    steps_reduction_factor: 0.5  # Half of normal steps
  
  # Edge analysis
  edge_analysis:
    direction_default: "vertical"
    position_default: 0
    seam_impact_initial: 0.0
    artifact_impact_initial: 0.0
  
  # Boundary tracking
  boundary_tracking:
    method_default: "unknown"
    progressive_method: "progressive"
    default_padding: 10

# ===================================================================
# OUTPUT AND COMPRESSION
# ===================================================================
output:
  # Compression settings
  compression:
    png_level: 0  # Lossless PNG (compress_level=0)
    jpeg_quality: 95
  
  # File naming and metadata
  metadata:
    timestamp_precision: 1000  # Millisecond precision
    operation_id_multiplier: 1000
  
  # Watermark settings (for mock pipeline)
  watermark:
    height: 40
    width: 120
    position_x: 10
    position_y: 10
    end_x: 110
    end_y: 30
    brightness_boost: 100

# ===================================================================
# VALIDATION AND SYSTEM REQUIREMENTS
# ===================================================================
system:
  # Python version requirements
  python:
    min_major: 3
    min_minor: 8
  
  # Hardware validation
  hardware:
    min_ram_gb: 16
    min_disk_space_gb: 50
    min_strategies: 4
  
  # VRAM simulation (for testing)
  simulation:
    mock_vram_24gb: 24576  # 24GB in MB
    vram_reduction_factor: 0.7
    operation_cost: 1000  # MB per operation

# ===================================================================
# BATCH PROCESSING AND LIMITS
# ===================================================================
batch:
  # Seed generation
  seed:
    hash_modulus: 4294967296  # 2^32
    random_seed_range: 1000
  
  # Error codes
  error_codes:
    success: 0
    config_error: 3
    processing_error: 4
    validation_error: 5
    adapter_error: 6
    general_error: 130

# ===================================================================
# EXPERIMENTAL FEATURES
# ===================================================================
experimental:
  # Hybrid adaptive strategy
  hybrid_adaptive:
    enabled: false
    extreme_ratio_thresholds: [4, 5]
    quality_fallback: 0.7
    vram_minimal: 512
  
  # Advanced processing
  advanced:
    frequency_analysis: true
    pattern_detection: true
    adaptive_quality: false

# ===================================================================
# DEBUGGING AND DEVELOPMENT
# ===================================================================
debug:
  # Stage saving
  save_stages: false
  save_tiles: false
  
  # Verbose output
  verbose: false
  
  # Cleanup settings
  cleanup:
    keep_temp_files: 5
    clear_cache_aggressive: false
  
  # Mock pipeline settings
  mock:
    color_ranges:
      red_min: 50
      red_max: 100
      green_min: 100
      green_max: 200
      blue_min: 100
      blue_max: 150
    
    noise_scale: 0.05
    enhancement_factor: 1.2

# ===================================================================
# CONFIGURATION METADATA
# ===================================================================
metadata:
  version: "1.0"
  total_values_configured: 979
  categories: 13
  description: "Comprehensive configuration capturing all hardcoded values in Expandor codebase"
  generated_date: "2025-01-27"
  source_analysis: "hardcoded_values_report.json"

# ===================================================================
# MIGRATION AND COMPATIBILITY
# ===================================================================
migration:
  # Legacy value mappings
  legacy_mappings:
    old_quality_threshold: "quality.validation.quality_threshold"
    old_vram_safety: "memory.vram.safety_factors.default"
    old_tile_size: "memory.vram.tiling.max_tile"
  
  # Default migrations
  default_updates:
    "output.formats.jpeg.quality": 95
    "vram.estimation.latent_multiplier": 4.5